### ISSUE TITLE
Incorporating Sass

### ISSUE THREAD

**Issue by silviascript** [ga-dc/pbj-project3#18]
Evening,

For the past couple of hours, I have tried, with difficulty, incorporating Sass into our express application. I've tried two different Sass NPM installations with no luck. I'm currently using the Node Sass Middleware, https://github.com/sass/node-sass-middleware. I keep receiving this error. I've tried changing the path multiple times and having a different setup.

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Siltastic/Sites/farmony-markets/node_modules/node-sass-middleware/middleware.js:3:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

``` javascript
// package.json
  "dependencies": {
    "body-parser": "^1.13.3",
    "express": "^4.13.3",
    "hbs": "^3.1.0",
    "node-sass-middleware": "^0.9.0",
    "pg": "^4.4.1",
    "pg-hstore": "^2.3.2",
    "sequelize": "^3.6.0"
  }

// index.js
// Require express.
// Connect express to application.
var express = require("express");
// var sassMiddleware = require('node-sass-middleware');
var app = express();

// Connect path middleware.
var path = require("path");

// Connecting to public assets.
// app.use(sassMiddleware({
//     /* Options */
//     src: __dirname + 'sass/styles',
//     dest: path.join(__dirname, 'public'),
//     debug: true,
//     outputStyle: 'compressed',
//     prefix:  '/prefix'  // Where prefix is at <link rel="stylesheets" href="prefix/style.css"/>
// }));

// var srcPath = __dirname + '/sass';
// var destPath = __dirname + '/public/styles';

// app.use(sassMiddleware({
//   src: srcPath,
//   dest: destPath,
//   debug: true,
//   outputStyle: 'compressed'
// })),

app.use("/public", express.static(path.join(__dirname + "/public")));
```

Help.

**Comment by RobertAKARobin** [comment]
Have you tried doing `require("node-sass")` instead of `require("node-sass-middleware")`? When I get a "cannot find module this-thing" error, I always try doing `npm install --save this-thing` and then `require("this-thing")`.

**Comment by silviascript** [comment]
@RobertAKARobin Thank you, Robin. I installed Node-Sass, but it didn't need the require in my index.js. I assume it just needed to connect to the source of the source. Now, I need to get it to work in the html.

**Comment by silviascript** [comment]
@RobertAKARobin I DID IT! IT FINALLY CONNECTED!

**Comment by RobertAKARobin** [comment]
Aww yiss.
