### ISSUE TITLE
Adding a twitter user to database

### ISSUE THREAD

**Issue by malissaromero** [ga-dc/pbj-project3#46]
I am trying to grab the twitter id and put it in the database but not sure how to do it. I am able to console. log the id but I tried to put it in a instance variable but it does not seem to be working. I put the instance in the callback because I thought that is when it should populate the database. Am I on the right track?

```
app.get("/auth/twitter/callback",
  passport.authenticate("twitter", { failureRedirect: "/login" }),
  function(req, res) {
    console.log(req.session)
    console.log(req.session.passport.user.id)
    console.log("HELLLLLOOOOOOOOOO")

    User.create({
      twitter_id: req.session.passport.user.id
    }).then(function(user){
    });

    res.redirect("/");
  }
);
```

**Comment by RobertAKARobin** [comment]
That looks right to me... When you say it doesn't seem to be working, do you mean you're getting an error? Have you used `psql` to poke around your database?

**Comment by malissaromero** [comment]
I am not getting an error but it is not populating the database. The database is empty every time I login.

**Comment by malissaromero** [comment]
Ok. I am getting an error that reads "TypeError: undefined is not a function" but is also not populating my database.

**Comment by RobertAKARobin** [comment]
Cool! What is it saying is undefined? Can you show the text of your error?

**Comment by malissaromero** [comment]
```
TypeError: undefined is not a function
    at /Users/malissacruzromero/wdi/projects/wanderlist/index.js:69:10
    at Layer.handle [as handle_request] (/Users/malissacruzromero/wdi/projects/wanderlist/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/malissacruzromero/wdi/projects/wanderlist/node_modules/express/lib/router/route.js:131:13)
    at complete (/Users/malissacruzromero/wdi/projects/wanderlist/node_modules/passport/lib/middleware/authenticate.js:243:13)
    at /Users/malissacruzromero/wdi/projects/wanderlist/node_modules/passport/lib/middleware/authenticate.js:250:15
    at pass (/Users/malissacruzromero/wdi/projects/wanderlist/node_modules/passport/lib/authenticator.js:421:14)
    at Authenticator.transformAuthInfo (/Users/malissacruzromero/wdi/projects/wanderlist/node_modules/passport/lib/authenticator.js:443:5)
    at /Users/malissacruzromero/wdi/projects/wanderlist/node_modules/passport/lib/middleware/authenticate.js:247:22
    at /Users/malissacruzromero/wdi/projects/wanderlist/node_modules/passport/lib/http/request.js:58:7
    at pass (/Users/malissacruzromero/wdi/projects/wanderlist/node_modules/passport/lib/authenticator.js:267:43)
    at serialized (/Users/malissacruzromero/wdi/projects/wanderlist/node_modules/passport/lib/authenticator.js:276:7)
    at /Users/malissacruzromero/wdi/projects/wanderlist/index.js:42:3
    at pass (/Users/malissacruzromero/wdi/projects/wanderlist/node_modules/passport/lib/authenticator.js:284:9)
    at Authenticator.serializeUser (/Users/malissacruzromero/wdi/projects/wanderlist/node_modules/passport/lib/authenticator.js:289:5)
    at IncomingMessage.req.login.req.logIn (/Users/malissacruzromero/wdi/projects/wanderlist/node_modules/passport/lib/http/request.js:48:29)
    at Strategy.strategy.success (/Users/malissacruzromero/wdi/projects/wanderlist/node_modules/passport/lib/middleware/authenticate.js:228:13)
```

**Comment by RobertAKARobin** [comment]
```
 at /Users/malissacruzromero/wdi/projects/wanderlist/index.js:69:10
```

It's pointing to line 69. What's on that line?

**Comment by malissaromero** [comment]
It is referring to this one: 

```
   User.create({
      twitter_id: req.session.passport.user.id
    }).then(function(user){
    });
```

**Comment by malissaromero** [comment]
Robin, helped me by adding this to my index.js. I first added only the User but connected it through my models and not through connection.js.

var Connection = require("./db/connection");
var User = Connection.models.User;

**Comment by RobertAKARobin** [comment]
+1000 points for adding your solution!!!!!!
